export {default as Header} from './Header'
export {default as Hero} from './Hero'
export {default as About} from './About'
export {default as Service} from './Service'
export {default as Teams} from './Teams'
export {default as Contact} from './Contact'
export {default as Footer} from './Footer'